# Generated by Django 4.1 on 2022-09-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="leave_reason",
        ),
    ]
