# Generated by Django 4.1 on 2022-09-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_remove_attendance_leave_reason"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "attendance", "created_at")},
        ),
    ]
