# Generated by Django 4.1 on 2022-09-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance",
                to="attendance.students",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_subject_attendance",
                to="attendance.subject",
            ),
        ),
    ]
