# Generated by Django 4.1 on 2022-09-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "created_at")},
        ),
    ]
